##############
### prd
##############
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 5s
    max-connections: 1000
    accept-count: 20
    threads:
      max: 200
spring:
  datasource:
    #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://shclub.synology.me:33306/edu # jdbc:mariadb://db:3306/edu
    username: edu
    #password: caravan
    #password: ENC(hk5/B+52K9XaD+BqzpFaHQ==)
    #password: New1234!
    password: ENC(cX5eDeWCal1Zen+LxWhQFXkqh44xdeDG)

  sql:
    init:
      platform: mariadb
#    hikari:
#      pool-name: hikari-cp
#      maximum-pool-size: 30
#      minimum-idle: 2
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true

# spring boot - actuator expose
management:
  endpoints:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,prometheus,metrics,caches,beans
  endpoint:
    health:
      probes:
        enabled: true
        
springdoc:
  show-actuator: true  # actuator swagger 노출
  swagger-ui:
    groups-order: DESC
    #operations-sorter: alpha
    #tags-sorter: alpha
    disable-swagger-default-url: true
    #doc-expansion: none

logging:
  level:
    com.kt.edu: trace
