server:
  tomcat:
    url-encoding: UTF-8
  servlet:
    context-path: /baseinfo
spring:
  application:
    name: baseinfo
  profiles:
    active: local
  banner:
    location: "classpath:banner.txt"
# cache 사용을 위해 cache name 설정
  cache:
    cache-names: employee
#  security:
#    user:
#      name: admin
#      password: admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080

# logging
logging:
  config: classpath:log4j2.xml

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  secret: CloudNativeKtEduSecretKey20240228CloudNativeKtEduSecretKey20240228CloudNativeKtEduSecretKey20240228

# app
app-info:
  app-name: "edu-spring-data-jdbc"
  title: "Cloud Native Edu API"
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
  user-id: "jake lee"
  org-id: "KT"
  desc: "EDU 관련 설명입니다."
  doc-url: "https://github.com/kt-cloudnative/education/"
  license: "Apache License"
  license_url: "https://github.com/kt-cloudnative/education/"
  version: "@app.build.timestamp@"
  doc-desc: "교육용"

