##############
### dev
##############
server:
  port: 8080
  servlet:
    context-path: /baseinfo
  tomcat:
    connection-timeout: 5s
    max-connections: 1000
    accept-count: 20
    threads:
      max: 200
# AWS RDS 변경
spring
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://rds.cluster-c92ik0osefy8.ap-northeast-2.rds.amazonaws.com:3306/test
    username: admin
    password: New1234!

# spring boot - actuator expose
management:
  endpoints:
    health:
      show-details: always
      enabled: true
    loggers:
      enabled: true  
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,prometheus,loggers,metrics,caches,beans
  endpoint:
    health:
      probes:
        enabled: true
        

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none

logging:
  level:
    com.kt.edu: trace
